name: Dev-Test

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-18.04
    env:
      RAILS_ENV: test

    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
        env:
          STACK_VERSION: 7.17.1
          xpack.security.enabled: false
          cluster.name: beckett-elasticsearch
          http.port: 9200
          discovery.type: single-node
        options: >-
          --health-cmd "curl http://localhost:9200/_cluster/health"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        ports:
          - 9200:9200
      postgres:
        image: postgres:10
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: user
          POSTGRES_DB: beckett_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1

      - run: sudo apt update
      - run: sudo apt install -y postgresql-client
      # - run: gem install bundler
      - run: bundle install
      - run: bundle exec rake db:create
      - run: bundle exec rake db:migrate
      - run: bundle exec rspec spec/